modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="photon"
version="1.0.0"
displayName="Photon"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Gaz, MCreator"

[[dependencies.photon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




